### ISSUE TITLE
Updated   Scrubs v2  Module 4.33

### ISSUE THREAD

**Issue by marson53** [jewbmx/ScrapeScraps#2]
Just updated to Scrubs v2  module 4.3.3
And got an error on scraping 
The scrape would start , then stop for about a minute  , then close 
Found it was two scrapers that was coursing  the error by going through them all 
Removed primewire  and moviesjoy   and  now works OK 
Hope this helps, if anyone else has this error  
Thank you

**Comment by jewbmx** [comment]
About to push another update in a few minutes that should fix any issues i know of. If you want you can turn those scrapers back on and see if the issue is resolved. If you have the same problem still let me know and i will remove those scrapers on the next update, gonna be doing a massive cleanse soon got my kodi exlax brewing up lol

**Comment by marson53** [comment]
Just to let you know primewire and moviesjoy , still having error with them enabled 
With them enabled it pauses & stops the count as it scrapes , then just opens with the results  
For me anyway , don't know if  anyone else has the same problem . 
 
Thanks for the addon and the updates

**Comment by jewbmx** [comment]
Ive seen it before but its usually with a whole lot going on so i dont notice it as a issue lol. They are ditched now and maybe worked on later
